# Generated by Django 4.1 on 2022-08-15 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("librarians", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarian",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="librarian",
            name="shift",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Matutino", "Morning"),
                    ("Vespertino", "Afternoon"),
                    ("Noturno", "Night"),
                    ("Não informado", "Default"),
                ],
                default="Não informado",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="librarian",
            name="ssn",
            field=models.PositiveIntegerField(default=12345),
            preserve_default=False,
        ),
    ]
