# Generated by Django 4.1 on 2022-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarians", "0002_librarian_birthdate_librarian_shift_librarian_ssn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarian",
            name="ssn",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
