# Generated by Django 4.1 on 2022-08-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
