# Generated by Django 4.1 on 2022-08-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="published_data",
            new_name="published_date",
        ),
    ]
