# Generated by Django 4.1 on 2022-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_published_data_book_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="11111111", max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
