# Generated by Django 4.1 on 2022-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("children", models.IntegerField()),
                (
                    "books",
                    models.ManyToManyField(related_name="authors", to="books.book"),
                ),
            ],
        ),
    ]
